db:
  build: ./db
  env_file: ./config/db/.env
  ports:
    - 5432:5432
backend:
  build: ./backend
  volumes:
    - ./backend:/app
  ports:
    - 8000:8000
  links:
    - db
ui:
  build: ./ui
  env_file: ./config/ui/.env
  volumes:
    - ./ui/src:/ui/src
  ports:
    - 8080:8080
  links:
    - backend
