# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetype',
            name='code',
            field=models.CharField(default='a', max_length=1, verbose_name='C\xf3digo'),
            preserve_default=False,
        ),
    ]
