# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20160427_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetype',
            name='code',
            field=models.CharField(max_length=1, unique=True, verbose_name='C\xf3digo'),
        ),
    ]
