# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20160427_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceType')),
            ],
        ),
        migrations.AlterModelOptions(
            name='devicebrand',
            options={'verbose_name': 'Marca de Dispositivo', 'verbose_name_plural': 'Marcas de Dispositivo'},
        ),
    ]
