# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20160428_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceBrand'),
            preserve_default=False,
        ),
    ]
