# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_device_device_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='asset',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='ownership',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
