# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_auto_20160428_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
