Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "provision/site.yml"
  end
  config.vm.synced_folder "../backend", "/usr/backend"
  config.vm.network :forwarded_port, guest: 8000, host: 9000
end
