#- name: add webupd8team
#  shell: echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu {{ ansible_distribution_release }} main" | tee -a /etc/apt/sources.list
#  sudo: yes

#- name: add key server
#  shell: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
#  sudo: yes

---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

    - name: verifica java
      apt: name={{item}}
      with_items:
       - oracle-java8-installer
      