---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
  - name: verifica git
    apt: update_cache=yes
  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - git
        
