---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
  - name: actualiza apt
    apt: update_cache=yes
  - name: verifica postgres y psycopg2
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: all
  sudo: yes
  sudo_user: postgres
  gather_facts: no

  vars:
    dbname: selene
    dbuser: postgres
    dbpassword: postgres

  tasks:
  - name: verifica que se cree la base de datos
    postgresql_db: name={{dbname}}

  - name: verifica que el usuario se pueda conectar
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL  role_attr_flags=CREATEDB,SUPERUSER

- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
  - name: verifica git
    apt: update_cache=yes
  - name: verifica git
    apt: name={{item}}
    with_items:
        - git

- hosts: all
  sudo: yes
  gather_facts: no

  tasks:
    - name: instala requerimientos de django
      command: pip install  -r ../requirements.txt 
