# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.IntegerField()),
                ('ownership', models.CharField(max_length=2)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('sequence', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['device_type'],
            },
        ),
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca de Dispositivo',
                'verbose_name_plural': 'Marcas de Dispositivo',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=1, unique=True, verbose_name='C\xf3digo')),
            ],
            options={
                'verbose_name': 'Tipo de Dispositivo',
                'verbose_name_plural': 'Tipos de Dispositivo',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceBrand'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceType'),
        ),
    ]
