# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-16 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Dispositivo', 'verbose_name_plural': 'Tipos de Dispositivo'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
    ]
