# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20160517_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceState'),
            preserve_default=False,
        ),
        migrations.RunSQL("insert into devices_devicestate values (default, 'Disponible')")
    ]
