# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-18 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_device_state'),
        ('devices', '0003_auto_20160516_2155'),
    ]

    operations = [
    ]
