# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20160427_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterModelOptions(
            name='devicetype',
            options={'verbose_name': 'Tipo de Dispositivo', 'verbose_name_plural': 'Tipos de Dispositivo'},
        ),
    ]
