# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-19 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Asignaci\xf3n de Dispositivos',
                'verbose_name_plural': 'Asignaciones de Dispositivos',
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Project'),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Assignment'),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        )
    ]
