# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20160519_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='devices',
            field=models.ManyToManyField(through='devices.DeviceAssignment', to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Project'),
        ),
    ]
