# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20160428_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
