# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 16:02
from __future__ import unicode_literals

from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_update_device_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_date',
            field=models.DateTimeField(default=timezone.now()),
        ),
    ]
