# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 17:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_assignment_assignment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assignment_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 17, 13, 17, 774974, tzinfo=utc)),
        ),
    ]
