# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20160504_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['device_type']},
        ),
        migrations.AddField(
            model_name='device',
            name='code',
            field=models.CharField(default='NA', max_length=11),
            preserve_default=False,
        ),
    ]
