# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_auto_20160513_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='code',
        ),
    ]
