# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 24, 23, 20, 16, 618795, tzinfo=utc)),
        ),
    ]
