# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_auto_20160524_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 30, 15, 47, 17, 832909, tzinfo=utc)),
        ),
    ]
