# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_remove_device_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sequence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
