# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20160530_1547'),
        ('devices', '0015_auto_20160526_1605'),
    ]

    operations = [
    ]
