# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0020_auto_20160602_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='first_assignment_date',
            new_name='laptop_begin_life',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='end_date',
            new_name='laptop_end_life',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Project'),
        ),
        migrations.AlterField(
            model_name='devicestatuslog',
            name='status_change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 16, 47, 35, 669971, tzinfo=utc)),
        ),
    ]
