# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-03 16:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_auto_20160603_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceassignment',
            options={'ordering': ['-assignment__assignment_date'], 'verbose_name': 'Asignación de Dispositivos', 'verbose_name_plural': 'Asignaciones de Dispositivos'},
        ),
        migrations.RemoveField(
            model_name='deviceassignment',
            name='assignment_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicestatuslog',
            name='status_change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 3, 16, 57, 22, 73534, tzinfo=utc)),
        ),
    ]
