# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 13:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20160606_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatuslog',
            name='status_change_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 7, 13, 26, 24, 868570, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('code', 'sequence')]),
        ),
    ]
