# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0026_adding_devices_from_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceassignment',
            name='actual_return_date',
            field=models.DateField(null=True),
        ),
    ]
