# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-30 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0030_adding_device_end_status_types'),
        ('devices', '0029_adding_devices_from_csv_file'),
    ]

    operations = [
    ]
