# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_auto_20160712_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_end_status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceEndStatusType'),
        ),
    ]
